### ISSUE TITLE
Error running pip install -e python

### ISSUE THREAD

**Issue by stokesj0001** [spear-sim/spear#255]
#### What platform am I on? What are my system specifications? Do I meet the minimum specifications for the Unreal Engine?

Windows. Not technically.

#### What am I attempting to do, what do I expect to happen, and what actually happened?

I was following https://github.com/isl-org/spear/blob/main/docs/getting_started.md and got to command,

`pip install -e python`

which produced the following error.

![spear_getting_started_error](https://github.com/isl-org/spear/assets/97129360/1eb1c22a-5f82-4e48-a3f5-3c659d487ed0)

I was able to resolve this error with: https://stackoverflow.com/questions/76129688/why-is-pip-install-gym-failing-with-python-setup-py-egg-info-did-not-run-succ

**Comment by mikeroberts3000** [comment]
Hi Jonathan, thanks for investigating this. What exactly was your solution? Did you modify the version numbers in our setup.py file?

**Comment by RachithP** [comment]
Looks like this issue should be reproducible with the mentioned package versions (of `setuptools`,  `wheel`, `pip`), but weirdly enough, I'm not able to reproduce it on my windows machine. I'm using `conda 4.11.0` and `python 3.8.18`. 

![Screenshot 2023-10-02 114029](https://github.com/isl-org/spear/assets/42787281/021dcec3-2585-42af-b32b-8d2b413aab83)

**Comment by mikeroberts3000** [comment]
That is strange. @RachithP has all the same versions of all the packages that @stokesj0001 has when this error occurred, as indicated by `pip list`.

**Comment by stokesj0001** [comment]
The workaround for me was to downgrade setuptools and wheel as mentioned in the stackoverflow post.

pip install setuptools==65.5.0 "wheel<0.40.0"

Then install the 0.21.0 version of gym

pip install gym==0.21.0

**Comment by mikeroberts3000** [comment]
Ah ok. That is good to know. So far, we haven't explicitly included `setuptools` or `wheel` in the dependencies listed in our `setup.py` file. But this issue is making me think that we should. We'll need to verify that the change works on all our supported platforms, so I'll leave this issue open until we have a chance to do that.

**Comment by stokesj0001** [comment]
I was using:

conda: 23.5.2
python: 3.8.18
pip: 22.3.1

**Comment by thias15** [comment]
> #### What platform am I on? What are my system specifications? Do I meet the minimum specifications for the Unreal Engine?
> Windows. Not technically.
> 
> #### What am I attempting to do, what do I expect to happen, and what actually happened?
> I was following https://github.com/isl-org/spear/blob/main/docs/getting_started.md and got to command,
> 
> `pip install -e python`
> 
> which produced the following error.
> 
> ![spear_getting_started_error](https://private-user-images.githubusercontent.com/97129360/271732406-1eb1c22a-5f82-4e48-a3f5-3c659d487ed0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNTAwMzUsIm5iZiI6MTcwMjM0OTczNSwicGF0aCI6Ii85NzEyOTM2MC8yNzE3MzI0MDYtMWViMWMyMmEtNWY4Mi00ZTQ4LWEzZjUtM2M2NTlkNDg3ZWQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDAyNTUzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2NTBjMmIyMWVkNzYyMzVjZjk1NzI3ZmMzNWFhZDk4YTg3YzcxOGI5NDYyMTE1ZDEwMjI5MTdmYTE4Yzk3NmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u9rE-tSjasKKbNAxCphtLOYnQ4jo1QvAj_B6Vr-7v5o)
> 
> I was able to resolve this error with: https://stackoverflow.com/questions/76129688/why-is-pip-install-gym-failing-with-python-setup-py-egg-info-did-not-run-succ

This error is probably due to the version of gym not being available for the OS. Try updating the setup.py in the python folder to a more recent version of gym, e.g. 0.26.x

**Comment by mikeroberts3000** [comment]
Thanks @thias15!

**Comment by mikeroberts3000** [comment]
The macOS, Windows, and Linux builds are currently working as expected.
