### ISSUE TITLE
Hello author, I would like to ask how the v0.5.0 version can create an object in the scene. I did not find any relevant code in that example program

### ISSUE THREAD

**Issue by Yinter-ai** [spear-sim/spear#299]
Hello author, I would like to ask how the v0.5.0 version can create an object in the scene. I did not find any relevant code in that example program

**Comment by mikeroberts3000** [comment]
Hi! The 0.5.0 pre-compiled binaries are somewhat out-of-date at this point. But we develop SPEAR actively on Windows, macOS, and Linux, so it should be straightforward to build for your platform. If you build the `SpearSim` executable from source in the `main` branch, then you'll be able to run all of our examples. Our `getting_started` example is very simple, and shows how to spawn a new object. Once you get that working, you can check out `import_stanford_dataset` and `control_simple_agent`, both of which spawn new objects.

**Comment by Yinter-ai** [comment]
hello author! Thank you for your reply very much . I encountered this problem while using the main branch to build the final step of the spear sim executable file, which is Python tools/run_uat. py -- unrereal. engine. dir path/to/UE.5.5- build - ok - stage - package - archive - pack. How can I solve this problem?Is this a compiler issue or some other library file issue? I haven't been able to solve it yet. Thank you for your answer.








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "spear-sim/spear"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月20日(星期三) 中午1:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [spear-sim/spear] Hello author, I would like to ask how the v0.5.0 version can create an object in the scene. I did not find any relevant code in that example program (Issue #299)





 
Hi! The 0.5.0 pre-compiled binaries are somewhat out-of-date at this point. But we develop SPEAR actively on Windows, macOS, and Linux, so it should be straightforward to build for your platform. If you build the SpearSim executable from source in the main branch, then you'll be able to run all of our examples. Our getting_started example is very simple, and shows how to spawn a new object. Once you get that working, you can check out import_stanford_dataset and control_simple_agent, both of which spawn new objects.

**Comment by mikeroberts3000** [comment]
Hi. Please take a bit of time to learn about what it takes to write a high-quality bug report that adheres to the usual best practices on GitHub. Then post your problem in a separate GItHub issue, and make sure to adhere to the recommendations you learned. Your most recent post does not adhere to the most basic recommendations for bug reports. For example, you don't even mention the error message or what you did to get to that error message. How could anyone possibly help you based on the information you provided?
