### ISSUE TITLE
I encountered the following problem while building my own spear-sim. Thank you for your answer

### ISSUE THREAD

**Issue by Yinter-ai** [spear-sim/spear#300]
#### What platform am I on? What are my system specifications? Do I meet the minimum specifications for the Unreal Engine?
 Windows computer based on x64 processor，64 bit operating system,Unreal Engine is 5.5

#### What commit of the `spear` repository am I on? Am I synced to a specific tag, or am I synced to the head of the `main` branch?
The operation I am currently performing is to use the main branch to build my own spear
#### What `SpearSim` executable am I using? Did I build it myself or download it? If I downloaded it, is my code synced to the correct tag?
I am trying to build my own spear sim

#### If I built my own executable, what were the command-line options I used to build it? Does my issue go away if I download a pre-compiled executable and sync my code to the correct tag?
This is the operation I used to build the command line  python tools/run_uat.py --unreal_engine_dir path/to/UE_5.5 -build -cook -stage -package -archive -pak   
The versions of compiler tools I use are Using Visual Studio 2022 14.38.33143 toolchain (D: \ Soft-ware \ visual_stdio \ consensus \ VC \ Tools \ MSVC \ 14.38.33130) and Windows 10.022621.0 SDK (D: \ Windows Kits \ 10) cmake 3.31.0-rc2,Anaconda Python24.9.2
#### What am I attempting to do, what do I expect to happen, and what actually happened?
I expected him to compile and successfully generate my own spear sim, but in the actual output results, there were many syntax errors in the. cpp and. h files

#### Here is the complete console output from when when I created the `spear.Env` object in my application.

![4b6dc40fee0cfb383857b26e2d7ace1](https://github.com/user-attachments/assets/6f05984f-da6b-41b8-9bfe-7190364cfb8c)

![1acc636609b9eca0624a8f6ad9af37e](https://github.com/user-attachments/assets/0e0255e5-b4c6-47bb-94d8-ee1a30b325bd)

![6341e4546bdf2fa8f9fddd48ed66809](https://github.com/user-attachments/assets/94cefe00-a528-4f87-8560-f17bba9bc9ff)

![060bb0e9528c634f1388e7bd0a82732](https://github.com/user-attachments/assets/e87c3420-76e6-4aeb-a586-aebcb57a024b)

![c495d4a5ce9be7c0ff0e972949b53de](https://github.com/user-attachments/assets/844eff73-05de-472f-aa18-791d8222af94)

![5d5feaf713fee0d2246f35b34fcebec](https://github.com/user-attachments/assets/b47bef69-9d7f-4e9b-b840-fce1f2de1777)

![5c106cdd37c7f7bebeb7b86d4ad1d2d](https://github.com/user-attachments/assets/b7c9b974-8c98-44c5-a2f5-0670096ac649)

![13eff3ddb3e85e3f2677c7248a194ee](https://github.com/user-attachments/assets/afb25f87-e399-400f-93e2-2ae53b140651)

![20ded9e91bd8a596df95740b209233a](https://github.com/user-attachments/assets/b54e8c28-0287-4743-ae48-b698885921cc)

![197fe6b4fb8be2cca4c9decef20e995](https://github.com/user-attachments/assets/beb33751-afa1-4fd6-8ecf-d31aca7b1e53)

![a14c829fe1ec6466e79aa42b80d0069](https://github.com/user-attachments/assets/45bd5c94-927f-4754-b16a-dbfc872d1125)

![f913235c2f4a8767845d03be2c825a8](https://github.com/user-attachments/assets/9711b580-4631-44b8-9edb-8f3b42ef2fe2)

![4f07c09631a067d7fb25ed8a31880d0](https://github.com/user-attachments/assets/bf91c7f8-adf9-47f8-843c-621630b39f05)

![14ada6e9b676d42612f3f02017958df](https://github.com/user-attachments/assets/f55fe7e9-3c0f-4a8f-a789-c2fd7273915e)

**Comment by mikeroberts3000** [comment]
Hello! Thank you for this detailed post. These error messages are in a language that I don't know, but I think I know what's going on. We've fixed similar issues recently on @rwang15's development machine but I don't remember exactly what we did. I'm still getting my Windows machine set up, but I'll make sure this is fixed in the next couple of days. I'll leave this issue open until we get all the necessary fixes checked in.

**Comment by mikeroberts3000** [comment]
Hi @Yinter-ai, I'm working on the Windows build now. At the moment, you're further than I am. Haha. I'm still working on building the third-party libraries.

**Comment by mikeroberts3000** [comment]
Windows build is fixed in 79bdd718063f9c3a449c20b56eb59f7b4d61560d. I can build `SpearSim` cleanly on a new Windows 11 PC with a fresh installation of Visual Studio 2022 and Unreal Engine 5.5. Please rename this issue to have a more informative name for other readers, and post any follow-up questions you have in new issues.
