### ISSUE TITLE
I encountered this issue with the submission of v0.5.0，But I don't have the ability to solve him.

### ISSUE THREAD

**Issue by Yinter-ai** [spear-sim/spear#302]
#### What platform am I on? What are my system specifications? Do I meet the minimum specifications for the Unreal Engine?
windows 64 bits  x64 
#### What commit of the `spear` repository am I on? Am I synced to a specific tag, or am I synced to the head of the `main` branch?
I encountered this issue with the submission of v0.5.0

#### What `SpearSim` executable am I using? Did I build it myself or download it? If I downloaded it, is my code synced to the correct tag?
I am using a downloaded executable file, and now my operation is to configure the Python environment of the unreal editor.

#### If I built my own executable, what were the command-line options I used to build it? Does my issue go away if I download a pre-compiled executable and sync my code to the correct tag?
I did not build my executable file, and I did not perform the last step of building the executable file (python tools/run_uat. py -- unrereal Engine. dir path/to/UE.5.2-- build config Development build ok stage package archive pak interactive cooking), because you explained to me that the executable file built is the same as the one you provided. My current problem is that I plan to perform the MuJoCo Interoperability operation, but I am stuck in this step python run. py -- mjcf_file path/to/speaker pipeline/partment_0000/mujoco-scene/main.mjcf

#### What am I attempting to do, what do I expect to happen, and what actually happened?
I encountered an issue where after using Spear sim v0.5.0, I plan to use MuJoCo interoperability operations. At present, my step is to run it to the (Python tool/configuration_iditor-Python. py -- unreal. engine. dir path/to/UE. 5.2) step, but there may be some library issues during this step. I hope it can successfully install these libraries onto the Unreal Engine compiler, but it has not occurred

#### Here is the complete console output from when when I created the `spear.Env` object in my application.
![13c2f71f4a444d542a28603293b54a5](https://github.com/user-attachments/assets/13c56aee-2262-446e-a40a-b712132d1d80)
![cc23ad6acf22125ce175759bef29270](https://github.com/user-attachments/assets/c208cffd-0394-4f58-8f16-3252c42ad6f6)
![f0d39270274606ec35a2456d6d0eed6](https://github.com/user-attachments/assets/d21fd6cc-796b-4463-845d-cd4ba318bd0b)
![c1407d80eb92c7a0cedbf24266f66d4](https://github.com/user-attachments/assets/1103b6e2-2107-4465-ab52-f67622834843)
![e08dccca3cb739ba704cece4b985377](https://github.com/user-attachments/assets/4f220a29-fa1f-43c0-96a4-0b6ef00e79e3)
![adb193cced1f373df9c561b6e77e1b7](https://github.com/user-attachments/assets/54e407b1-c530-4739-83e5-21379e2d0417)

**Comment by mikeroberts3000** [comment]
> _My current problem is that I plan to perform the MuJoCo Interoperability operation, but I am stuck in this step python run. py -- mjcf_file path/to/speaker pipeline/partment_0000/mujoco-scene/main.mjcf_

> _At present, my step is to run it to the (Python tool/configuration_iditor-Python. py -- unreal. engine. dir path/to/UE. 5.2) step, but there may be some library issues during this step._

Which is it? You're saying that you're stuck on two different steps.
