### ISSUE TITLE
I am confused

### ISSUE THREAD

**Issue by ryudious** [spear-sim/spear#305]
I am not sure what the precompiled build does?  I can fly around and that is it as it seems.  I see the CMD saying what is in the photo about the NavMeshes though.   What is supposed to happen?  In the Screenshots I seen a robot etc and it looked cool to try lol
![Screenshot 2024-12-10 181349](https://github.com/user-attachments/assets/5490c81e-f20a-48d7-bf25-1d0f2121f588)

**Comment by mikeroberts3000** [comment]
If you re-write your question more carefully I'll respond more carefully (lol)
